In [1]:
from DataProcessing.American.DataParser import DataParser
from DataProcessing.American.FeatureExtractionSecond import FeatureExtractionSecond
from ModelDataGenerator import ModelDataGenerator
from DataGenerator import DataGenerator
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import sys
import tensorflow as tf
import os

log_str = 1

/usr/local/lib/python2.7/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
/usr/local/lib/python2.7/site-packages/sklearn/grid_search.py:42: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. This module will be removed in 0.20.
  DeprecationWarning)
Using TensorFlow backend.


In [2]:
def Get_Sample_Data():
    df = DataParser().AmericanCombo_i(2)
    return df

# df0 = DataParser().AmericanCombo_i(-2)
# df1 = DataParser().AmericanCombo_i(1)

# df2 = DataParser().AmericanCombo_i(2)

In [3]:
def print_me(df_IN):
    df_A = df_IN
#     df_A = df_A.loc[df_IN['st'] == 'WI']
#     df_A = df_A.loc[df_IN['svcg_cycle'] == 200204]
#     print len(df_A['id_loan'].unique())
#     df_A = df_A.drop_duplicates(subset='svcg_cycle')
    df_A['rt'] = df_A['rt_default_per_state']
    df_A['occr_def'] = df_A['active_loans_per_state']
    df_A['occr_al'] = df_A['active_loans_per_state']
    df_A = df_A.sort_values(['occr_al'], ascending=[False])
    print df_A[['id_loan', 'svcg_cycle','st', 'rt', 'occr_al', 'occr_def']]
    
# print_me(df0) 

In [4]:
# df_current = DataParser().AmericanCombo_i(-2)
 

# Data Preparation -  OHE 

In [5]:
# dataset = DataParser().AmericanCombo_i(0)
# df_OHE = FeatureExtractionSecond().filter_main(dataset)
# DataParser()._write_HDFStore_OHE(df_OHE, -1)

In [6]:
df_OHE = DataParser()._read_HDFStore_OHE(-2)
modelDataGenerator = ModelDataGenerator(False)
modelDataGenerator.load_data(df_OHE, DataGenerator().ActiveTargetClass)

--- Resampling Took : 622.57636714 seconds ---
--- Resampling Took : 22.4182288647 seconds ---
Training Class ratios BEFORE,  50.0 : 50.0
Training Class ratios BEFORE,  292593.0 : 292593.0(raw numbers)
Validation Class ratios BEFORE,  50.0 : 50.0
Validation Class ratios BEFORE,  72994.0 : 72994.0(raw numbers)
Size: 632001.104 mb


In [8]:
from Train import Train
import DataProcessing.American.Globals as Globals
import argparse as _argparse

tf.app.flags._global_parser = _argparse.ArgumentParser()
tf.summary.FileWriterCache.clear()
train = Train(modelDataGenerator)



In [19]:
log_str = log_str + 1
train.FLAGS.log_dir = (Globals.get_log_dir() + Globals.CURRENT_DESCRIPTION + str(log_str)).format(cwd=os.getcwd())
train.run_log_dir = os.path.join(train.FLAGS.log_dir, 'bs_{bs}'.format(bs=train.FLAGS.batch_size))
train.checkpoint_path = os.path.join(train.run_log_dir, 'model.ckpt')

train.FLAGS.weight_ratio = 1.05
train.FLAGS.learning_rate = 0.0000001
train.FLAGS.max_steps = 25000

train.FLAGS.validation_iterations = 1000

In [20]:
train.main()

Graph


/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py:509: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  return np.fromstring(tensor.tensor_content, dtype=dtype).reshape(shape)
/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py:509: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  return np.fromstring(tensor.tensor_content, dtype=dtype).reshape(shape)
/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py:509: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  return np.fromstring(tensor.tensor_content, dtype=dtype).reshape(shape)
/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py:509: DeprecationWarning: The bina

INFO:tensorflow:Summary name Learning Rate is illegal; using Learning_Rate instead.


/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/tensor_util.py:509: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  return np.fromstring(tensor.tensor_content, dtype=dtype).reshape(shape)


step 19, epoc 1, accuracy on validation set : 0.484375
step 39, epoc 1, accuracy on validation set : 0.5
step 59, epoc 1, accuracy on validation set : 0.546875
step 79, epoc 1, accuracy on validation set : 0.546875
step 99, epoc 1, accuracy on validation set : 0.515625
step 119, epoc 1, accuracy on validation set : 0.5
step 139, epoc 1, accuracy on validation set : 0.46875
step 159, epoc 1, accuracy on validation set : 0.40625
step 179, epoc 1, accuracy on validation set : 0.484375
step 199, epoc 1, accuracy on validation set : 0.609375
step 219, epoc 1, accuracy on validation set : 0.59375
step 239, epoc 1, accuracy on validation set : 0.546875
step 259, epoc 1, accuracy on validation set : 0.484375
step 279, epoc 1, accuracy on validation set : 0.546875
step 299, epoc 1, accuracy on validation set : 0.453125
step 319, epoc 1, accuracy on validation set : 0.546875
step 339, epoc 1, accuracy on validation set : 0.515625
step 359, epoc 1, accuracy on validation set : 0.484375
step 379, 

KeyboardInterrupt: 

In [ ]:
Confusion Matrix label_good_bad_loan_0: 
[[21084  4354]
 [   16   146]]

TPR (Recall): 0.9012
TNR (Specificity): 0.8288
ROC AUC: 0.8650

Accuracy: 0.8293
train.FLAGS.weight_ratio = 1.7400
train.FLAGS.learning_rate = 0.00010000
train.FLAGS.max_steps = 10000
0.9012, 0.8288, 0.8650, 0.8293, 1.7400, 0.00010000, 10000

In [ ]:
Confusion Matrix label_good_bad_loan_0: 
[[20017  5439]
 [    9   135]]

TPR (Recall): 0.9375
TNR (Specificity): 0.7863
ROC AUC: 0.8619

Accuracy: 0.7872
train.FLAGS.weight_ratio = 1.6700
train.FLAGS.learning_rate = 0.00010000
train.FLAGS.max_steps = 10000
0.9375, 0.7863, 0.8619, 0.7872, 1.6700, 0.00010000, 10000

In [ ]:
Confusion Matrix label_good_bad_loan_0: 
[[22939  2531]
 [   23   107]]

TPR (Recall): 0.8231
TNR (Specificity): 0.9006
ROC AUC: 0.8619

Accuracy: 0.9002
train.FLAGS.weight_ratio = 1.1800
train.FLAGS.learning_rate = 0.00010000
train.FLAGS.max_steps = 10000
0.8231, 0.9006, 0.8619, 0.9002, 1.1800, 0.00010000, 10000

In [ ]:
[[19388  6048]
 [    6   158]]

TPR (Recall): 0.9634
TNR (Specificity): 0.7622
ROC AUC: 0.8628

Accuracy: 0.7635
train.FLAGS.weight_ratio = 1.1650
train.FLAGS.learning_rate = 0.00010000
train.FLAGS.max_steps = 10000
0.9634, 0.7622, 0.8628, 0.7635, 1.1650, 0.00010000, 10000


In [ ]:
Confusion Matrix label_good_bad_loan_0: 
[[24473   907]
 [   89   131]]

TPR (Recall): 0.595454545455
TNR (Specificity): 0.96426319937
AUC: 0.7798588724120639

train.FLAGS.weight_ratio = 1.08
train.FLAGS.learning_rate = 0.0001
train.FLAGS.max_steps = 16000


In [ ]:
--------------------------------------------------- (old ratios)

In [ ]:
--------------------------------------------------- (-1 below)

In [ ]:
Confusion Matrix label_good_bad_loan_0: 
[[21890  3522]
 [   29   159]]

TPR (Recall): 0.845744680851
TNR (Specificity): 0.861404061074
AUC: 0.853574370962286

train.FLAGS.weight_ratio = 1.2357
train.FLAGS.learning_rate = 0.0001
train.FLAGS.max_steps = 10000

In [ ]:
--------------------------------------------------- (-2 below)

In [ ]:
Confusion Matrix label_good_bad_loan_0: 
[[22022  3443]
 [   20   115]]


TPR (Recall): 0.851851851852
TNR (Specificity): 0.864794816415
AUC: 0.8583233341332693
    
train.FLAGS.weight_ratio = 0.7725 * 1.221
train.FLAGS.learning_rate = 0.0001
train.FLAGS.max_steps = 16000

In [ ]:
Confusion Matrix label_good_bad_loan_0: 
[[20296  5150]
 [   12   142]]


TPR (Recall): 0.922077922078
TNR (Specificity): 0.797610626425
AUC: 0.8598442742512536
    
train.FLAGS.weight_ratio = 0.7725 * 1.223
train.FLAGS.learning_rate = 0.0001
train.FLAGS.max_steps = 8000

In [ ]:
Confusion Matrix label_good_bad_loan_0: 
[[18397  7061]
 [    3   139]]


TPR (Recall): 0.978873239437
TNR (Specificity): 0.722641212978
AUC: 0.8507572262074292
    
train.FLAGS.weight_ratio = 0.7725 * 1.24
train.FLAGS.learning_rate = 0.0001
train.FLAGS.max_steps = 20000

In [ ]:
Confusion Matrix label_good_bad_loan_0: 
[[13079 12354]
 [    0   167]]


TPR (Recall): 1.0
TNR (Specificity): 0.51425313569
AUC: 0.7571265678449259
    
train.FLAGS.weight_ratio = 0.7725 * 1.224
train.FLAGS.learning_rate = 0.0001
train.FLAGS.max_steps = 8000

In [ ]:
Confusion Matrix label_good_bad_loan_0: 
[[22927  2519]
 [   29   125]]

TPR (Recall): 0.811688311688
TNR (Specificity): 0.901006052032
AUC: 0.8563471818600327
    
train.FLAGS.weight_ratio = 0.7725 * 1.22
train.FLAGS.learning_rate = 0.0001
train.FLAGS.max_steps = 8000


In [ ]:
Confusion Matrix label_good_bad_loan_0: 
[[23417  2033]
 [   39   111]]


TPR (Recall): 0.74
TNR (Specificity): 0.920117878193
AUC: 0.830058939096267
    
train.FLAGS.weight_ratio = 0.7725 * 1.22
train.FLAGS.learning_rate = 0.0001
train.FLAGS.max_steps = 16000

In [ ]:
Confusion Matrix label_good_bad_loan_0: 
[[23254  2210]
 [   38    98]]


TPR (Recall): 0.720588235294
TNR (Specificity): 0.913210807414
AUC: 0.8168995213542534
        
train.FLAGS.weight_ratio = 0.7725 * 1.2357
train.FLAGS.learning_rate = 0.0001
train.FLAGS.max_steps = 10000

In [ ]:
Confusion Matrix label_good_bad_loan_0: 
[[22975  2499]
 [   38    88]]


TPR (Recall): 0.698412698413
TNR (Specificity): 0.901899976447
AUC: 0.8001563374296357
    
train.FLAGS.weight_ratio = 0.7725 * 1.224
train.FLAGS.learning_rate = 0.0001
train.FLAGS.max_steps = 16000

In [ ]:
Confusion Matrix label_good_bad_loan_0: 
[[25308   150]
 [  126    16]]


TPR (Recall): 0.112676056338
TNR (Specificity): 0.994107942494
AUC: 0.5533919994157736
    
train.FLAGS.weight_ratio = 0.7725 * 1.225
train.FLAGS.learning_rate = 0.0001
train.FLAGS.max_steps = 25000

# ROC Curve

In [ ]:
import numpy as np
from itertools import cycle

from sklearn import svm, datasets
from sklearn.metrics import roc_curve, auc
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import label_binarize
from sklearn.multiclass import OneVsRestClassifier
from scipy import interp
from ModelDataGenerator import ModelDataGenerator
from skmultilearn.problem_transform import LabelPowerset
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_predict
from sklearn import metrics





mdg = ModelDataGenerator()

X = np.concatenate((mdg._train[0], mdg._validation[0]))
Y = np.concatenate((mdg._train[1], mdg._validation[1]))
y = LabelPowerset().transform(Y)


# # Import some data to play with
# iris = datasets.load_iris()
# X = iris.data
# y = iris.target

# # Binarize the output
y = label_binarize(y, classes=[0, 1])
n_classes = y.shape[1]

# # Add noisy features to make the problem harder
# random_state = np.random.RandomState(5)
# n_samples, n_features = X.shape
# print X.shape
# X = np.c_[X, random_state.randn(n_samples, 200 * n_features)]

# shuffle and split training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.5,
                                                    random_state=0)

# Learn to predict each class against the other
classifier = OneVsRestClassifier(svm.SVC(kernel='linear', probability=True,
                                 random_state=random_state))
y_score = classifier.fit(X_train, y_train).decision_function(X_test)


# # Learn to predict each class against the other
# classifier = LinearRegression()
# y_score = cross_val_predict(classifier,X_train, y_train, cv=6)

# accuracy = metrics.r2_score(y_train, y_score)
print("LinR Accuracy: %.3f ") % (accuracy)

# Compute ROC curve and ROC area for each class
fpr = dict()
tpr = dict()
roc_auc = dict()
for i in range(n_classes):
    fpr[i], tpr[i], _ = roc_curve(y_test[:, i], y_score[:, i])
    roc_auc[i] = auc(fpr[i], tpr[i])

# Compute micro-average ROC curve and ROC area
fpr["micro"], tpr["micro"], _ = roc_curve(y_test.ravel(), y_score.ravel())
roc_auc["micro"] = auc(fpr["micro"], tpr["micro"])


lw = 2



In [ ]:
import plotly.plotly as py
import plotly.graph_objs as go
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
init_notebook_mode(connected=True)


# Compute macro-average ROC curve and ROC area

data = []

# fpr = fpr + 0.5

# First aggregate all false positive rates
all_fpr = np.unique(np.concatenate([fpr[i] for i in range(n_classes)]))

# Then interpolate all ROC curves at this points
mean_tpr = np.zeros_like(all_fpr)
for i in range(n_classes):
    mean_tpr += interp(all_fpr, fpr[i], tpr[i])

# Finally average it and compute AUC
mean_tpr /= n_classes

fpr["macro"] = all_fpr
tpr["macro"] = mean_tpr
roc_auc["macro"] = auc(fpr["macro"], tpr["macro"])

# Plot all ROC curves
# data = []
# trace1 = go.Scatter(x=fpr["micro"], y=tpr["micro"],
#                     mode='lines', 
#                     line=dict(color='deeppink', width=lw, dash='dot'),
#                     name='micro-average ROC curve (area = {0:0.2f})'
#                            ''.format(roc_auc["micro"]))
# data.append(trace1)

# trace2 = go.Scatter(x=fpr["macro"], y=tpr["macro"],
#                     mode='lines', 
#                     line=dict(color='navy', width=lw, dash='dot'),
#                     name='macro-average ROC curve (area = {0:0.2f})'
#                           ''.format(roc_auc["macro"]))
# data.append(trace2)

colors = cycle(['aqua', 'darkorange', 'cornflowerblue'])
for i, color in zip(range(n_classes), colors):
    trace3 = go.Scatter(x=fpr[i], y=tpr[i],
                        mode='lines', 
                        line=dict(color=color, width=lw),
                        name='ROC curve of class {0} (area = {1:0.2f})'
                        ''.format(i, roc_auc[i]))
    data.append(trace3)

trace4 = go.Scatter(x=[0, 1], y=[0, 1], 
                    mode='lines', 
                    line=dict(color='black', width=lw, dash='dash'),
                    showlegend=False)

layout = go.Layout(title='Some extension of Receiver operating characteristic to multi-class',
                   xaxis=dict(title='False Positive Rate'),
                   yaxis=dict(title='True Positive Rate'))

fig = go.Figure(data=data, layout=layout)
iplot(fig)